services:
  postgres:
    image: postgres:15
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
    driver: local